export type UserRole = 'student' | 'company' | 'admin';

export interface Profile {
  id: string;
  role: 'student' | 'admin';
  full_name: string | null;
  email: string | null;
  skills: string | null;
  education: string | null;
  experience: string | null;
  created_at: string;
  // Extended editorial UI fields
  avatar_url?: string | null;
  headline?: string | null;
  university?: string | null;
  degree?: string | null;
  graduation_year?: string | null;
  location?: string | null;
  bio?: string | null;
  portfolio_url?: string | null;
  github_url?: string | null;
  linkedin_url?: string | null;
  resume_text?: string | null;
  interests?: string[];
}

export interface Company {
  id: string;
  company_name: string;
  email: string | null;
  linkedin_url: string | null;
  website_url: string | null;
  about: string | null;
  location: string | null;
  is_verified: boolean;
  created_at: string;
  // Extended editorial UI fields
  logo_url?: string | null;
  industry?: string | null;
  company_size?: string | null;
  founded_year?: string | null;
  mission?: string | null;
  team_members?: { name: string; role: string; avatar?: string }[];
}

export interface Internship {
  id: string;
  company_id: string;
  title: string;
  description: string | null;
  requirements: string | null;
  role_type: string | null;
  duration: string | null;
  stipend: string | null;
  location: string | null;
  application_deadline: string | null;
  is_active: boolean;
  created_at: string;
  company?: Company;
  // Extended editorial UI fields
  department?: string | null;
  work_mode?: 'Remote' | 'Hybrid' | 'On-site';
  experience_level?: string | null;
  skills?: string[];
  responsibilities?: string[];
  what_you_learn?: string[];
  applicant_count?: number;
  featured?: boolean;
}

export interface Application {
  id: string;
  internship_id: string;
  student_id: string;
  cover_note: string | null;
  match_score: number | null; // 0 - 100% computed by AI
  ai_feedback: string | null; // Recruiter insight generated by AI
  status: 'applied' | 'under_review' | 'shortlisted' | 'selected' | 'rejected';
  created_at: string;
  internship?: Internship;
  student?: Profile;
  stage_history?: { stage: string; timestamp: string }[];
}

export interface NotificationItem {
  id: string;
  recipient_role: UserRole;
  recipient_id?: string;
  title: string;
  message: string;
  type: 'application' | 'status_change' | 'opportunity_alert' | 'verification';
  read: boolean;
  created_at: string;
  action_url?: string;
}

export interface PlatformStats {
  totalStudents: number;
  totalCompanies: number;
  unverifiedCompanies: number;
  totalInternships: number;
  totalApplications: number;
}
